### ISSUE TITLE
Error: Disconnected Client disconnected from CONNECTED state (transport close)

### ISSUE THREAD

**Issue by zloirock** [Onslip/karma-playwright-launcher#1]
Hi.

I'm replacing `puppeteer` + `karma-chrome-launcher` to `playwright` + `@onslip/karma-playwright-launcher` for calling QUnit tests on Karma. All works fine, asserts works as expected, however in the Karma output I see messages about disconnections of browsers marked as errors (but without exiting the process with an error):

![image](https://user-images.githubusercontent.com/2213682/144847934-978f1927-9c38-46e1-825b-b2e2414a224e.png)

It's not critical, but sometimes it can confuse.

Configuration: https://github.com/zloirock/core-js/blob/bb0690dc28aa9bdc0e042325168e413eb7375592/karma.conf.js

**Comment by unlikelyzero** [comment]
Thank you for this implementation. We are also seeing this issue @zloirock

**Comment by zloirock** [comment]
It seems it's fixed in `0.3.0`.
